### PR TITLE
Webp support

### PR DESCRIPTION
**Pull request by ahtinurme**
* Added Cwebp as the optimizer
* Only part missing is the images from the documentation, but that will be fixed if it's merged in (https://spatie.github.io/image-optimizer/examples/image.webp and https://spatie.github.io/image-optimizer/examples/image-optimized.webp)

### CODE REVIEW

**Comment by freekmurze** [comment]
Cool PR, I'd like to merge it in, but the tests should be fixed first.

**Comment by ahtinurme** [comment]
Yeah, I needed to changed the optimizer in the process. Fixing the tests also.

**Comment by ahtinurme** [comment]
One thing I would actually need help with is getting the base optimization parameters right, I copied ones from here (https://medium.com/@vinhlh/how-i-apply-webp-for-optimizing-images-9b11068db349), but I believe they can be more optimized, but I don't have time to experiment with this further.

**Comment by ahtinurme** [comment]
For some reason, Travis doesn't accept the webp file provided. I'll take a look at this some other day.

**Comment by cron13** [comment]
Good day, what about with this request?
Will it be merged?

**Comment by rubenvanassche** [comment]
Checked this locally and on a forge provisioned server and indeed the tests are working fine! Probably the travis-ci container has an older version of webp? We could check this out by enabling the debug mode on the tarvis-ci container, what do you think @freekmurze ?

**Comment by freekmurze** [comment]
Yeah, sure, go ahead! Thanks for testing this.

**Pull request merged**
