### PR TITLE
Add Webp optimizer

### PR DESCRIPTION
**Pull request by Spirit13**
Add class
Add example images
Update readme
Add tests

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice PR, but won't this change the format of all input files to webp?

**Comment by Spirit13** [comment]
> Nice PR, but won't this change the format of all input files to webp?

No. This just create new file from source(`-o` option is output file name, optimizer just replace original extension to new one `webp`).
Notice. Optimized image will by different quality when optimizer added as first(webp will be created from original image) or as last(webp will be created from optimized image) in chain.

**Comment by freekmurze** [comment]
Are you sure the output isn't a webp file with the `png` or `jpeg` extension? When looking at the docs is see no evidence that cwebp outputs anything else than `webp`
https://developers.google.com/speed/webp/docs/cwebp

**Comment by Spirit13** [comment]
I think, i did mistake in this saying
> optimizer just replace original extension to new one webp 
because didn't understand your first question correctly.
This update optimize image and save it as webp.

**Comment by freekmurze** [comment]
So, this is a breaking change because now all images will be converted to the `webp` format. People probably don't want to have the format of their images changed.

Closing this for now. Ping me to reopen if I misunderstood something.

**Comment by Spirit13** [comment]
> So, this is a breaking change because now all images will be converted to the `webp` format. People probably don't want to have the format of their images changed.
> 
> Closing this for now. Ping me to reopen if I misunderstood something.

Not 100% correctly. Current functionality will not be broken, just one more image will be created if `OptimizerChainFactory` is used. But I can remove cwebp from `OptimizerChainFactory`. And every user will be decide to use Cwebp or not.

**Comment by freekmurze** [comment]
I don't think I want any conversion being done from one format to another. The goal of this package is to optimize files without changing their format.

**Comment by Spirit13** [comment]
> I don't think I want any conversion being done from one format to another. The goal of this package is to optimize files without changing their format.

Ok. Understand it.

**Pull request closed without merging**
