### PR TITLE
Add support for --skip-if-larger option of pngquant

### PR DESCRIPTION
**Pull request by MrPropre**
Check #139 for more details

### CODE REVIEW

**Comment by MrPropre** [comment]
The CI build failed with `error: Process errored with error: unknown option '--disable={cleanupIDs,removeViewBox}'`
It seems that in [SVGO 2.0](https://github.com/svg/svgo/releases/tag/v2.0.0), `--enable` and `--disable` flags are removed.
[https://github.com/svg/svgo/issues/1356#issuecomment-782834313](https://github.com/svg/svgo/issues/1356#issuecomment-782834313)

**Comment by MrPropre** [comment]
For now, I have fixed the SVGO version to 1.3.2 because 2.x is not backward compatible.

**Comment by freekmurze** [comment]
I'm thinking that this will break it for people that are on v2 of pngquant

**Comment by MrPropre** [comment]
@freekmurze I think you are talking about SVGO. Feel free to propose another solution for SVGO 2 users. This PR is initially for pngquant but tests did not pass because of SVGO 2.

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
